translate_text_task:
  description: >
    Translate the following text into FALC using provided editorial and design rules.

    You must first consult the available icons list:

    {icon_list}

    Use only the icon keys listed here and embed them with the format: [[ICON:icon_key]].

    Do NOT use emojis.
    Do NOT invent new keys.

    ONLY use icons from the list above in the format: [[ICON:KEY]]

    You have access to a Knowledge base tool that contains example translations.
    First, check if any reference model matches the topic using the ReferenceModelRetriever tool.

    Tool usage hint:
    Summarize the original text, and ask a question by calling the tool like:
        query: "What reference example matches a document about 'your summary' ?"

    If you find a good match, follow its style and reuse structure or tone.
    Focus on short sentences, active voice, familiar vocabulary, and structure clarity.

    Text to translate:
    {original_text}
  expected_output: >
    Your output MUST be a dictionary with the following fields:
    "header": "Sender details and organization block"
    "recipient": "Recipient address block"
    "subject": "Document subject line"
    "body_sections": "[Section titles or text blocks, one per paragraph or heading]"
    "footer": "Polite sign-off"

    The subject body sections MUST contain the best icon placeholder in the format [[ICON:KEY]]

    This structure will be used to format the final Word document.

    Emojis ARE STRICLY PROHIBITED.

  agent: falc_translator

generate_docx_task:
  description: >
    Convert the structured text into a .docx document using predefined
    formatting guidelines:
    Arial font, size 10 for body text, size 8 for headers, spacing 1.5x.
  expected_output: >
    A Word (.docx) document saved to output/ directory,
    named `falc_translated_output.docx`
  agent: falc_document_designer
