translate_text_task:
  description: >
    Translate the following text into FALC using provided editorial and design rules.

    You must first consult the available icons list:

    {icon_list}

    Use only the icon keys listed here and embed them with the format: [[ICON:icon_key]].

    Do NOT use emojis.
    Do NOT invent new keys.

    ONLY use icons from the list above in the format: [[ICON:KEY]]

    You have access to a Knowledge base tool that contains example translations.
    First, check if any reference model matches the topic using the ReferenceModelRetriever tool.

    Tool usage hint:
    Summarize the original text, and ask a question by calling the tool like:
        query: "What reference example matches a document about 'your summary' ?"

    If you find a good match, follow its style and reuse structure or tone.
    Focus on short sentences, active voice, familiar vocabulary, and structure clarity.

    Text to translate:
    {original_text}
  expected_output: >
    Your output MUST be a dictionary with the following fields:
    "header": "Sender details and organization block"
    "recipient": "Recipient address block"
    "subject": "Document subject line"
    "body_sections": "[Section titles or text blocks, one per paragraph or heading]"
    "footer": "Polite sign-off"

    The paragraphs in the subject body sections MUST contain the best icon placeholder in the format [[ICON:KEY]]
    DO not add icon in the other sections.

    This structure will be used to format the final Word document.

    Emojis ARE STRICLY PROHIBITED.

  agent: falc_translator


rewrite_original_doc_task:
  description: >
    Update the original Word file at {original_doc_path} using the FALC translation.

    Replace:
    - Paragraph at index {subject_index} with the translated subject
    - Paragraphs at indexes {body_indexes} with the translated body

    The following values will be passed:
    - subject
    - body_sections
    - header (optional)
    - recipient (optional)
    - footer (optional)

  expected_output: >
    A .docx file rewritten in-place, saved as `output/falc_finalized_output.docx`.

  agent: falc_document_designer
