translate_text_task:
  description: >
    Translate the following text into FALC using provided editorial and design rules.

    You have access to a Knowledge base tool that contains example translations.
    First, check if any reference model matches the topic using the ReferenceModelRetriever tool.

    Tool usage hint:
    Summarize the original text, and ask a question by calling the tool like:
        query: "What reference example matches a document about 'your summary' ?"

    If you find a good match, follow its style and reuse structure or tone.
    Focus on short sentences, active voice, familiar vocabulary, and structure clarity.

    Text to translate:
    {original_text}
  expected_output: >
    A markdown version of the FALC-compliant text, respecting the structure and
    accessible language rules.
  agent: falc_translator

quality_check_task:
  description: >
    Review the FALC text for accuracy, compliance with FALC rules, and structure.
    Correct non-compliant sections. Explain changes if needed.
  expected_output: >
    Finalized markdown with FALC-compliant text and explanation of adjustments.
  agent: falc_quality_analyst

generate_docx_task:
  description: >
    Convert the markdown text into a .docx document using predefined
    formatting guidelines:
    Arial font, size 10 for body text, size 8 for headers, spacing 1.5x.
  expected_output: >
    A Word (.docx) document saved to output/ directory,
    named `falc_translated_output.docx`
  agent: falc_document_designer

validate_visual_design_task:
  description: >
    Validate that the generated Word document adheres to FALC visual design.
    Check typography, spacing, alignment, and section layout.
  expected_output: >
    A short markdown report confirming if the document matches FALC
    visual standards or requires changes.
  agent: falc_visual_checker
