translate_text_task:
  description: >
    Translate the following text into FALC using provided editorial and design rules.

    You have access to a Knowledge base tool that contains example translations.
    First, check if any reference model matches the topic using the ReferenceModelRetriever tool.

    Tool usage hint:
    Summarize the original text, and ask a question by calling the tool like:
        query: "What reference example matches a document about 'your summary' ?"

    If you find a good match, follow its style and reuse structure or tone.
    Focus on short sentences, active voice, familiar vocabulary, and structure clarity.

    You **must call** the `FalcIconLookupTool` to see which icons are available
    before you decide to include any icons in your translation.

    These icons are helpful visual cues (emojis) used to simplify understanding.
    Do not invent your own icons — you may only use icons that are explicitly listed by the tool.

    If you think a section would benefit from a visual symbol, choose one from the list provided
    and include it in the appropriate location.

    Text to translate:
    {original_text}
  expected_output: >
    Your output MUST be a dictionary with the following fields:
    "header": "Sender details and organization block"
    "recipient": "Recipient address block"
    "subject": "Document subject line"
    "body_sections": "[Section titles or text blocks, one per paragraph or heading]"
    "footer": "Polite sign-off"

    This structure will be used to format the final Word document.
    You are not allowed to invent icons. Use only those provided by the icon lookup tool.

    Make sure to check with a human in FRENCH if the draft is good before finalizing your answer.

  agent: falc_translator

generate_docx_task:
  description: >
    Convert the structured text into a .docx document using predefined
    formatting guidelines:
    Arial font, size 10 for body text, size 8 for headers, spacing 1.5x.
  expected_output: >
    A Word (.docx) document saved to output/ directory,
    named `falc_translated_output.docx`
  agent: falc_document_designer
